services:
  postgres:
    image: postgres:16-alpine
    container_name: flash-sale-postgres
    environment:
      POSTGRES_USER: flashsale
      POSTGRES_PASSWORD: flashsale123
      POSTGRES_DB: flashsale
    ports:
      - "2077:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis-dev
    ports:
      - "6379:6379"

volumes:
  pgdata:
