server:
  port: 8083

database:
  driver: postgres
  host: payment-db
  port: 5432
  user: flashsale
  password: flashsale123
  dbname: payment_db
  sslmode: disable
  timezone: Asia/Shanghai

kafka:
  brokers:
    - kafka:9092
  produce_topic: payment-events
  consumer_groups:
    - group_id: payment-service-group
      topic: order-events

outbox:
  interval_ms: 500

payment:
  success_rate: 1.0
